# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Passtimes' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Passtimes

pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod 'MaterialComponents/Snackbar'
pod 'Kingfisher', '~> 4.0'
pod 'FSCalendar'

end
